// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "Catch-all reverse proxy that forwards requests to the configured Greenfield RPC endpoint. JSON-RPC requests for broadcast_tx_sync/commit may be intercepted by middleware for fee guarantee and bucket provisioning.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "RPC Proxy"
                ],
                "summary": "Proxy to Greenfield RPC",
                "responses": {
                    "200": {
                        "description": "Proxied response from Greenfield RPC"
                    }
                }
            },
            "post": {
                "description": "Catch-all reverse proxy that forwards requests to the configured Greenfield RPC endpoint. JSON-RPC requests for broadcast_tx_sync/commit may be intercepted by middleware for fee guarantee and bucket provisioning.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "RPC Proxy"
                ],
                "summary": "Proxy to Greenfield RPC",
                "responses": {
                    "200": {
                        "description": "Proxied response from Greenfield RPC"
                    }
                }
            }
        },
        "/guarantor": {
            "get": {
                "description": "Returns the proxy's on-chain Greenfield address and the BNB spend limit configured for each fee grant.\nClients call this endpoint before constructing transactions to discover which address to set as ` + "`" + `fee_granter` + "`" + `.\nThe fee guarantee middleware only activates when a transaction's ` + "`" + `fee_granter` + "`" + ` matches the returned address.\nThe ` + "`" + `amount` + "`" + ` field reflects the per-grant spend cap.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Guarantor"
                ],
                "summary": "Get fee guarantor info",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.GuarantorResponse"
                        }
                    },
                    "403": {
                        "description": "PROVISIONER_UNAVAILABLE -- bucket provisioning not configured",
                        "schema": {
                            "$ref": "#/definitions/ion-greenfield-proxy_internal_apperror.AppError"
                        }
                    }
                }
            }
        },
        "/health-check": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "ok: true",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    }
                }
            }
        },
        "/sp/{path}": {
            "get": {
                "description": "Decodes the base64url-encoded SP origin from the path, validates it against the known SP allowlist, and reverse-proxies the request. The Host header may carry a bucket subdomain for virtual-hosted style access.",
                "tags": [
                    "Storage Provider Proxy"
                ],
                "summary": "Proxy to Storage Provider",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Base64url-encoded SP origin optionally followed by /subpath",
                        "name": "path",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Proxied response from the storage provider"
                    },
                    "400": {
                        "description": "MISSING_TARGET_SP / INVALID_TARGET_SP",
                        "schema": {
                            "$ref": "#/definitions/ion-greenfield-proxy_internal_apperror.AppError"
                        }
                    },
                    "403": {
                        "description": "INVALID_SP_SCHEME / SP_VALIDATION_UNAVAILABLE / UNKNOWN_SP / INVALID_SP_HOST",
                        "schema": {
                            "$ref": "#/definitions/ion-greenfield-proxy_internal_apperror.AppError"
                        }
                    },
                    "503": {
                        "description": "SP_LIST_UNAVAILABLE",
                        "schema": {
                            "$ref": "#/definitions/ion-greenfield-proxy_internal_apperror.AppError"
                        }
                    }
                }
            },
            "put": {
                "description": "Decodes the base64url-encoded SP origin from the path, validates it against the known SP allowlist, and reverse-proxies the request. The Host header may carry a bucket subdomain for virtual-hosted style access.",
                "tags": [
                    "Storage Provider Proxy"
                ],
                "summary": "Proxy to Storage Provider",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Base64url-encoded SP origin optionally followed by /subpath",
                        "name": "path",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Proxied response from the storage provider"
                    },
                    "400": {
                        "description": "MISSING_TARGET_SP / INVALID_TARGET_SP",
                        "schema": {
                            "$ref": "#/definitions/ion-greenfield-proxy_internal_apperror.AppError"
                        }
                    },
                    "403": {
                        "description": "INVALID_SP_SCHEME / SP_VALIDATION_UNAVAILABLE / UNKNOWN_SP / INVALID_SP_HOST",
                        "schema": {
                            "$ref": "#/definitions/ion-greenfield-proxy_internal_apperror.AppError"
                        }
                    },
                    "503": {
                        "description": "SP_LIST_UNAVAILABLE",
                        "schema": {
                            "$ref": "#/definitions/ion-greenfield-proxy_internal_apperror.AppError"
                        }
                    }
                }
            },
            "post": {
                "description": "Decodes the base64url-encoded SP origin from the path, validates it against the known SP allowlist, and reverse-proxies the request. The Host header may carry a bucket subdomain for virtual-hosted style access.",
                "tags": [
                    "Storage Provider Proxy"
                ],
                "summary": "Proxy to Storage Provider",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Base64url-encoded SP origin optionally followed by /subpath",
                        "name": "path",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Proxied response from the storage provider"
                    },
                    "400": {
                        "description": "MISSING_TARGET_SP / INVALID_TARGET_SP",
                        "schema": {
                            "$ref": "#/definitions/ion-greenfield-proxy_internal_apperror.AppError"
                        }
                    },
                    "403": {
                        "description": "INVALID_SP_SCHEME / SP_VALIDATION_UNAVAILABLE / UNKNOWN_SP / INVALID_SP_HOST",
                        "schema": {
                            "$ref": "#/definitions/ion-greenfield-proxy_internal_apperror.AppError"
                        }
                    },
                    "503": {
                        "description": "SP_LIST_UNAVAILABLE",
                        "schema": {
                            "$ref": "#/definitions/ion-greenfield-proxy_internal_apperror.AppError"
                        }
                    }
                }
            },
            "delete": {
                "description": "Decodes the base64url-encoded SP origin from the path, validates it against the known SP allowlist, and reverse-proxies the request. The Host header may carry a bucket subdomain for virtual-hosted style access.",
                "tags": [
                    "Storage Provider Proxy"
                ],
                "summary": "Proxy to Storage Provider",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Base64url-encoded SP origin optionally followed by /subpath",
                        "name": "path",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Proxied response from the storage provider"
                    },
                    "400": {
                        "description": "MISSING_TARGET_SP / INVALID_TARGET_SP",
                        "schema": {
                            "$ref": "#/definitions/ion-greenfield-proxy_internal_apperror.AppError"
                        }
                    },
                    "403": {
                        "description": "INVALID_SP_SCHEME / SP_VALIDATION_UNAVAILABLE / UNKNOWN_SP / INVALID_SP_HOST",
                        "schema": {
                            "$ref": "#/definitions/ion-greenfield-proxy_internal_apperror.AppError"
                        }
                    },
                    "503": {
                        "description": "SP_LIST_UNAVAILABLE",
                        "schema": {
                            "$ref": "#/definitions/ion-greenfield-proxy_internal_apperror.AppError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internal_handler.GuarantorResponse": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string",
                    "example": "0x1234567890abcdef1234567890abcdef12345678"
                },
                "amount": {
                    "type": "string",
                    "example": "0.001"
                }
            }
        },
        "ion-greenfield-proxy_internal_apperror.AppError": {
            "description": "Structured error response with a machine-readable code and a human-readable message.",
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "INVALID_TARGET_SP"
                },
                "error": {
                    "type": "string",
                    "example": "invalid URL in target SP"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "ION Greenfield Proxy API",
	Description:      "Transparent reverse proxy between ION clients and BNB Greenfield (RPC + Storage Provider endpoints).\n\nMost requests pass through unmodified. The middleware layer intercepts three classes of requests:\n\n1. **StorageProviders ABCI Query** -- rewrites SP endpoint URLs so all subsequent SP traffic is routed back through this proxy (`/sp/{base64}`).\n2. **CreateBucket Broadcast** -- intercepts `MsgCreateBucket` where `bucket_name == creator_address`, creates the bucket using the proxy's signing key, grants object CRUD permissions and SP delegation to the user, and returns a synthetic broadcast result.\n3. **Fee Allowance Grant** -- for `broadcast_tx_sync`/`commit` containing `MsgCreateObject`, `MsgDelegateCreateObject`, `MsgUpdateObjectContent`, `MsgDeleteObject`, or `MsgDeleteBucket` with `fee_granter == proxy_address`, submits a short-lived `MsgGrantAllowance` on-chain before forwarding the original transaction.\n\nThe proxy listens on two transports: HTTP/TCP (localhost) and ADNL/RLDP (ION overlay network). Both feed into the same Gin engine and middleware stack.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
