import type { Language } from "./types";

// TODO: replace with real API call
const LANGUAGES: Language[] = [
  { code: "am", name: "Amharic", flag: "\u{1F1EA}\u{1F1F9}" },
  { code: "ar", name: "Arabic", flag: "\u{1F1F8}\u{1F1E6}" },
  { code: "hy", name: "Armenian", flag: "\u{1F1E6}\u{1F1F2}" },
  { code: "az", name: "Azerbaijani", flag: "\u{1F1E6}\u{1F1FF}" },
  { code: "bn", name: "Bangla", flag: "\u{1F1E7}\u{1F1E9}" },
  { code: "eu", name: "Basque", flag: "\u{1F1EA}\u{1F1F8}" },
  { code: "bg", name: "Bulgarian", flag: "\u{1F1E7}\u{1F1EC}" },
  { code: "my", name: "Burmese", flag: "\u{1F1F2}\u{1F1F2}" },
  { code: "ca", name: "Catalan", flag: "\u{1F1EA}\u{1F1F8}" },
  { code: "ckb", name: "Central Kurdish", flag: "\u{1F1EE}\u{1F1F6}" },
  { code: "zh", name: "Chinese", flag: "\u{1F1E8}\u{1F1F3}" },
  { code: "cs", name: "Czech", flag: "\u{1F1E8}\u{1F1FF}" },
  { code: "da", name: "Danish", flag: "\u{1F1E9}\u{1F1F0}" },
  { code: "dv", name: "Divehi", flag: "\u{1F1F2}\u{1F1FB}" },
  { code: "nl", name: "Dutch", flag: "\u{1F1F3}\u{1F1F1}" },
  { code: "en", name: "English", flag: "\u{1F1EC}\u{1F1E7}" },
  { code: "eo", name: "Esperanto", flag: "\u{1F30D}" },
  { code: "et", name: "Estonian", flag: "\u{1F1EA}\u{1F1EA}" },
  { code: "fi", name: "Finnish", flag: "\u{1F1EB}\u{1F1EE}" },
  { code: "fr", name: "French", flag: "\u{1F1EB}\u{1F1F7}" },
  { code: "ka", name: "Georgian", flag: "\u{1F1EC}\u{1F1EA}" },
  { code: "de", name: "German", flag: "\u{1F1E9}\u{1F1EA}" },
  { code: "el", name: "Greek", flag: "\u{1F1EC}\u{1F1F7}" },
  { code: "gu", name: "Gujarati", flag: "\u{1F1EE}\u{1F1F3}" },
  { code: "ht", name: "Haitian Creole", flag: "\u{1F1ED}\u{1F1F9}" },
  { code: "he", name: "Hebrew", flag: "\u{1F1EE}\u{1F1F1}" },
  { code: "hi", name: "Hindi", flag: "\u{1F1EE}\u{1F1F3}" },
  { code: "hu", name: "Hungarian", flag: "\u{1F1ED}\u{1F1FA}" },
  { code: "is", name: "Icelandic", flag: "\u{1F1EE}\u{1F1F8}" },
  { code: "id", name: "Indonesian", flag: "\u{1F1EE}\u{1F1E9}" },
  { code: "it", name: "Italian", flag: "\u{1F1EE}\u{1F1F9}" },
  { code: "ja", name: "Japanese", flag: "\u{1F1EF}\u{1F1F5}" },
  { code: "kn", name: "Kannada", flag: "\u{1F1EE}\u{1F1F3}" },
  { code: "kk", name: "Kazakh", flag: "\u{1F1F0}\u{1F1FF}" },
  { code: "km", name: "Khmer", flag: "\u{1F1F0}\u{1F1ED}" },
  { code: "ko", name: "Korean", flag: "\u{1F1F0}\u{1F1F7}" },
  { code: "lo", name: "Lao", flag: "\u{1F1F1}\u{1F1E6}" },
  { code: "lv", name: "Latvian", flag: "\u{1F1F1}\u{1F1FB}" },
  { code: "lt", name: "Lithuanian", flag: "\u{1F1F1}\u{1F1F9}" },
  { code: "ms", name: "Malay", flag: "\u{1F1F2}\u{1F1FE}" },
  { code: "ml", name: "Malayalam", flag: "\u{1F1EE}\u{1F1F3}" },
  { code: "mr", name: "Marathi", flag: "\u{1F1EE}\u{1F1F3}" },
  { code: "ne", name: "Nepali", flag: "\u{1F1F3}\u{1F1F5}" },
  { code: "no", name: "Norwegian", flag: "\u{1F1F3}\u{1F1F4}" },
  { code: "or", name: "Odia", flag: "\u{1F1EE}\u{1F1F3}" },
  { code: "ps", name: "Pashto", flag: "\u{1F1E6}\u{1F1EB}" },
  { code: "fa", name: "Persian", flag: "\u{1F1EE}\u{1F1F7}" },
  { code: "pl", name: "Polish", flag: "\u{1F1F5}\u{1F1F1}" },
  { code: "pt", name: "Portuguese", flag: "\u{1F1F5}\u{1F1F9}" },
  { code: "pa", name: "Punjabi", flag: "\u{1F1EE}\u{1F1F3}" },
  { code: "ro", name: "Romanian", flag: "\u{1F1F7}\u{1F1F4}" },
  { code: "ru", name: "Russian", flag: "\u{1F1F7}\u{1F1FA}" },
  { code: "sr", name: "Serbian", flag: "\u{1F1F7}\u{1F1F8}" },
  { code: "sd", name: "Sindhi", flag: "\u{1F1F5}\u{1F1F0}" },
  { code: "si", name: "Sinhala", flag: "\u{1F1F1}\u{1F1F0}" },
  { code: "sl", name: "Slovenian", flag: "\u{1F1F8}\u{1F1EE}" },
  { code: "es", name: "Spanish", flag: "\u{1F1EA}\u{1F1F8}" },
  { code: "sv", name: "Swedish", flag: "\u{1F1F8}\u{1F1EA}" },
  { code: "tl", name: "Tagalog", flag: "\u{1F1F5}\u{1F1ED}" },
  { code: "ta", name: "Tamil", flag: "\u{1F1EE}\u{1F1F3}" },
  { code: "te", name: "Telugu", flag: "\u{1F1EE}\u{1F1F3}" },
  { code: "th", name: "Thai", flag: "\u{1F1F9}\u{1F1ED}" },
  { code: "bo", name: "Tibetan", flag: "\u{1F1E8}\u{1F1F3}" },
  { code: "tr", name: "Turkish", flag: "\u{1F1F9}\u{1F1F7}" },
  { code: "uk", name: "Ukrainian", flag: "\u{1F1FA}\u{1F1E6}" },
  { code: "ur", name: "Urdu", flag: "\u{1F1F5}\u{1F1F0}" },
  { code: "ug", name: "Uyghur", flag: "\u{1F1E8}\u{1F1F3}" },
  { code: "vi", name: "Vietnamese", flag: "\u{1F1FB}\u{1F1F3}" },
  { code: "cy", name: "Welsh", flag: "\u{1F3F4}" },
];

export async function fetchLanguages(): Promise<Language[]> {
  return LANGUAGES;
}
