export enum IdentityErrorCode {
  PASSKEY_NOT_AVAILABLE = 'PASSKEY_NOT_AVAILABLE',
  PASSKEY_CANCELLED = 'PASSKEY_CANCELLED',
  PASSKEY_VALIDATION_FAILED = 'PASSKEY_VALIDATION_FAILED',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  USER_DEACTIVATED = 'USER_DEACTIVATED',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  UNAUTHENTICATED = 'UNAUTHENTICATED',
  NETWORK_ERROR = 'NETWORK_ERROR',
  UNKNOWN = 'UNKNOWN',
  RESTRICTED_REGION = 'RESTRICTED_REGION',
  TWO_FA_REQUIRED = 'TWO_FA_REQUIRED',
  INVALID_TWO_FA_CODE = 'INVALID_TWO_FA_CODE',
  TWO_FA_NOT_CONFIGURED = 'TWO_FA_NOT_CONFIGURED',
  INVALID_NICKNAME = 'INVALID_NICKNAME',
  NICKNAME_ALREADY_EXISTS = 'NICKNAME_ALREADY_EXISTS',
  NICKNAME_RESERVED = 'NICKNAME_RESERVED',
  INVALID_RECOVERY_CREDENTIALS = 'INVALID_RECOVERY_CREDENTIALS',
  INVALID_SIGNATURE = 'INVALID_SIGNATURE',
  INVALID_EMAIL = 'INVALID_EMAIL',
  PASSWORD_FLOW_NOT_AVAILABLE = 'PASSWORD_FLOW_NOT_AVAILABLE',
  WALLET_NOT_FOUND = 'WALLET_NOT_FOUND',
  SERVER_ERROR = 'SERVER_ERROR',
}

export class IdentityError extends Error {
  constructor(
    public readonly code: IdentityErrorCode,
    message: string,
    public override readonly cause?: unknown,
  ) {
    super(message);
    this.name = 'IdentityError';
  }
}
