export const Routes = {
  Splash: 'Splash',
  GetStarted: 'GetStarted',
  Main: 'Main',
  Catalog: 'Catalog',
  ChatPreview: 'ChatPreview',
  ProxyTest: 'ProxyTest',
  StorageTest: 'StorageTest',
  AuthFlow: 'AuthFlow',

  Sheet: {
    Auth: 'Sheet/Auth',
    WalletViewManagement: 'Sheet/WalletViewManagement',
    NicknameReserved: 'Sheet/NicknameReserved',
    IdentityKeyNameNote: 'Sheet/IdentityKeyNameNote',
    Verify: 'Sheet/Verify',
    LinkDevice: 'Sheet/LinkDevice',
    VerifyOnOtherDevice: 'Sheet/VerifyOnOtherDevice',
    AddBiometrics: 'Sheet/AddBiometrics',
    AddPasskeyCredentials: 'Sheet/AddPasskeyCredentials',
    CreatePost: 'Sheet/CreatePost',
    InvalidCredentials: 'Sheet/InvalidCredentials',
    ConfirmPassword: 'Sheet/ConfirmPassword',
    RestoreSuccess: 'Sheet/RestoreSuccess',
    GeneralError: 'Sheet/GeneralError',
    MediaPicker: 'Sheet/MediaPicker',
    GalleryPermissionDenied: 'Sheet/GalleryPermissionDenied',
    CameraPermissionDenied: 'Sheet/CameraPermissionDenied',
    CancelPost: 'Sheet/CancelPost',
  },

  WalletView: {
    Switcher: 'WalletViewSwitcher',
    Manage: 'WalletViewManage',
    Create: 'WalletViewCreate',
    Edit: 'WalletViewEdit',
    DeleteConfirm: 'WalletViewDeleteConfirm',
  },

  Auth: {
    GetStarted: 'GetStarted',
    PasswordRegister: 'PasswordRegister',
    PasskeyRegister: 'PasskeyRegister',
    RestoreIdentity: 'RestoreIdentity',
    RestoreWithRecoveryCreds: 'RestoreWithRecoveryCreds',
    RestoreSetNewPassword: 'RestoreSetNewPassword',
    ProfileSetup: 'ProfileSetup',
    SelectLanguages: 'SelectLanguages',
    DiscoverCreators: 'DiscoverCreators',
    Notifications: 'Notifications',
  },
} as const;
